### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by ghost** [07th-mod/tatarigoroshi#69] opened 2018-11-15 00:36 UTC
I spent a long time today trying to get Tatarigoroshi running and for some reason it kept crashing.
I have tried it on both the Steam and DRM free GOG release, I keep getting the same error again and again.
I saw this thread https://github.com/07th-mod/tatarigoroshi/issues/66 and it's almost the same thing that was happening to me. When I installed everything and opened the game it would either show me a bugged purple font and no main menu options or plain old crash, this depended on what version of the UI I installed the Steam version or DRM free (in that order). At the beginning I had the GOG release, when I tried to patch it  I would get the first error, I thought the installer could be mixing up the Steam UI patch with the correct one (this being the DRM free patch), but when I switched them manually the game wouldn't even start it just crashed. When I switched to the Steam release to see if I could get it to work I got the former error again.
The only solution I found was by not applying the patch at all. And even that only worked on the Steam release because on the DRM free the game just wouldn't work without the UI (black background, no sprites, no voices just sound and text).
If I'm being to confusing please do tell me, I hope you guys could help me see why it is not working.
Ps: I used both the 1.19 and 1.20 versions of the installer and downloaded all files for manual tries on the guide.

**Comment by ItaloKnox** [comment] 2018-11-15 00:39
Hi,

I'll need the ``output_log.txt`` file that should be inside the game folder (on ``HigurashiEp03_Data``) and the logs from the installer if you still have them. I'm pretty sure we have more information on this issue so I'm going to tag @enumag here to see if he remembers something.

For now just upload the logs you have so we can check them out.

**Comment by ghost** [comment] 2018-11-15 01:16
At one point I switched disks so I have 2 Logs folders. And the output log is from the crash folder.

[Logs1.zip](https://github.com/07th-mod/tatarigoroshi/files/2583230/Logs1.zip)
[output_log.txt](https://github.com/07th-mod/tatarigoroshi/files/2583234/output_log.txt)
[Logs.zip](https://github.com/07th-mod/tatarigoroshi/files/2583247/Logs.zip)

**Comment by ItaloKnox** [comment] 2018-11-15 01:21
Okay, the first thing I can see is that you are running version ``5.3.4p1`` instead of ``5.4.0f1`` (current on Steam). I think that's why you are running into compatibility issues since we have to use modded .dlls and UI files that are dependent on the latest version of the game.

I suggest you contact GOG if they are selling an old version of the game, or uninstall the game and install it again on Steam to see if the game comes updated this time.

However, I will still leave this open since we have a similar issue on Discord and I would like to get @enumag's confirmation on this since he was following the other issue instead of me.

**Comment by TellowKrinkle** [comment] 2018-11-15 01:22
GOG has 5.3.4p1.  That's why we have two separate `assets` files, one for Steam and one for DRM-Free for Tatarigoroshi
IIRC the game complains a lot more if you mismatch those, so I would guess that isn't the issue

**Comment by ItaloKnox** [comment] 2018-11-15 01:25
You're right, I was in charge of doing that and I completely forgot about it. lol

Other than that, I can see that the UI mod is not working as intended since the game accuses it to be corrupted. I suggest going to our [wiki](https://github.com/07th-mod/guide/wiki/Higurashi-Part-1---Voice-and-Graphics-Patch) and reinstalling the UI mod manually to see if it changes anything.

**Comment by ghost** [comment] 2018-11-15 01:29
I have done it both with the installer and without it. Same error.
In regards to the Steam version I did try it out but I do not own it I only have a copie of the GOG release.

**Comment by ItaloKnox** [comment] 2018-11-15 01:31
We have a similar situation ongoing on Discord so you two probably are running into the same issue. Tatari, GOG, and the crashes. We will probably need some time to dig into this a little further.

I'll do my best to keep you updated.

**Comment by ghost** [comment] 2018-11-15 01:35
Thanks.
Hope you guys can figure it out, keep up the good work.

**Comment by TellowKrinkle** [comment] 2018-11-15 01:55
Could you try with this instead?
[Tatarigoroshi-UI_MG.zip](https://github.com/07th-mod/tatarigoroshi/files/2583340/Tatarigoroshi-UI_MG.zip)

**Comment by ghost** [comment] 2018-11-15 12:18
I had the normal UI and switched the file. It works.
Thanks you.

**Comment by enumag** [comment] 2018-11-17 20:07
We updated the installer to use the fixed UI as well. Closing.

**Closed as completed by enumag** 2018-11-17 20:07 UTC
