### ISSUE TITLE
Programmer looking forward to help

### ISSUE THREAD

**Issue by cucochukoluko** [07th-mod/tatarigoroshi#2] opened 2016-07-02 20:31 UTC
Basically I'm a huge fan of 07h expansion's games, and I've played the higurashi steam series with the patches that you guys made. I saw recently that you need help with the code, since the one who was doing that job "dissapeared". So... Tell me exactly what do you need. Which language are you using? Are you working with an existing game engine? etc

**Comment by ItaloKnox** [comment] 2016-07-02 21:40
Hey! Thanks for the interest. :)

Here's a complete breakdown of what needs to be done:
1. First, the resources. The full list of voice files and its respectives dialogs can be found [here](https://github.com/higurashi-mod/tatarigoroshi/tree/master/dev).
2. Using the list as a base, it should search each string and find a match for the text. Sometimes the string is broken into multiple lines, so be aware of that.

[Example here](https://github.com/higurashi-mod/tatarigoroshi/blob/master/dev/s19.txt#L8971~L8972):

```
S19/25/502500018    「そうっすよ。
S19/25/502500019 心をこめて頑張りましたって言って、コックが消し炭みたいなハンバーグを持ってきたら、それにお金を払います？」
```

[Both lines can be found here](https://github.com/higurashi-mod/tatarigoroshi/blob/master/Scripts/tata_002.txt#L1590~L1593):

```
    OutputLine(NULL, "「そうっすよ。",
           NULL, "\"That's right.", Line_WaitForInput);
    OutputLine(NULL, "心をこめて頑張りましたって言って、コックが消し炭みたいなハンバーグを持ってきたら、それにお金を払います？",
           NULL, " If a chef brought you burned steak and said they put their spirit into it and tried hard, would you pay them?", Line_ContinueAfterTyping);
```
1. Since you found a match, now the code needs to place a line before the dialog on the original script. Line is `PlaySE(4, "<voice file>", 128, 64);`
2. The script above should look like this when edited:

```
    PlaySE(4, "S19/25/502500018", 128, 64);
    OutputLine(NULL, "「そうっすよ。",
           NULL, "\"That's right.", Line_WaitForInput);
    PlaySE(4, "S19/25/502500019", 128, 64);
    OutputLine(NULL, "心をこめて頑張りましたって言って、コックが消し炭みたいなハンバーグを持ってきたら、それにお金を払います？",
           NULL, " If a chef brought you burned steak and said they put their spirit into it and tried hard, would you pay them?", Line_ContinueAfterTyping);
```
- After finding a match, placing the line with the voice file, then the code should move to the next dialog until the script is done.

A few points to consider:
- You have more than 20 voice lists to parse, so in my opinion the best option is to find the first match manually and then run the code using the list. Some dialogs are really common during the novel, and the voice lists actually **cover the entire game** (until the very last chapter).
- The code can be done in any language as long as it works. Take care to not break the identation or japanese text. Identation should be a tab instead of four spaces.
- As you can see, the script doesn't really follow a language. So as long as the line is placed in the right place, there's nothing to worry.
- Engine is Unity, but the mod doesn't require it to work, we're only working with the scripts.

If you need something else, just tell me and I'll be here to help!

**Comment by enumag** [comment] 2016-07-04 05:55
@cucochukoluko Are you working on this then? I should be able to write it as well but it's pointless to do so if you're on it. Also can you post your work here on GitHub so that we have the source code this time?

@ItaloKnox This is basically what the original script did, right? Is there anything else you would like the new script to do? Did the original have any edge-case issues we should be careful about?

**Comment by ItaloKnox** [comment] 2016-07-04 06:10
Yeah, however I never touched nor seen the original script. My coding skills are still very limited to work on something like this, so I can only offer the assumption that the original script worked like that.

Anyway, I think it's hard to have a perfect script, so if we can maintain the margin of error around 30% like always, there's nothing to improve on. The biggest issue from the previous script is that sometimes the logic failed and it would skip a sentence or two, even though the sentence _matched_. Perhaps improving the logic and giving it a small margin of freedom would make it work better.

Also, @enumag, I don't know if @cucochukoluko is working on the script at this moment, but are you interested in working on a similar script for Umineko? The logic on Umineko should be a lot clearer to work on.

**Comment by enumag** [comment] 2016-07-04 06:30
Why not? But we need to wait for Umineko to come out first, right?

**Comment by ItaloKnox** [comment] 2016-07-04 06:35
It's coming out this friday already. I can't gift you the Steam version (regional restrictions as always), but if you want I can share with you my MangaGamer version.

I think there 99% of chances of Umineko following the exact same script pattern of Umineko. We can't reuse Higurashi's code, but for Umineko we have the script from the previous engine with all voices already placed. It's "just" a version of Higurashi a lot more messy, but with a lot less matching errors.

**Comment by enumag** [comment] 2016-07-04 08:33
Not that I want to steal @cucochukoluko his credit but after thinking about it more it really seamed easy. After two hours of work I have a working prototype of the script for Higurashi.

Of course there are quite a few cases where it failes:
- Some lines are split to two OutputLine commands in the tata script
  - This wouldn't be easy to fix. Not sure if it's worth fixing.
- Everything that has a tilde (~) in it beacuse the scripts and the dev files use different character for it.
  - Fixed by replacing this character during the search.
- Lines that do not match completely (like missing dot at the end of the line)
  - Not easy to fix but probably needed. The problem is that it will probably be extremely slow.
- Lines that have more than one match in the dev files. (Most commonly the "..." lines.)
  - I could use some tips how to determine which line to use. Remembering which dev file contained the last matched line and prefering that often isn't enough. There are many cases with multiple matches within one dev file.

I'm pretty sure there are other cases I'm not yet aware of.

**Comment by ItaloKnox** [comment] 2016-07-04 08:41
Looks great, I think you are not so far from the original script.

Can you upload tata_001 and/or tata_tips_01 after running your script? Maybe the issues you described are just the usual issues we fix while editing.

**Comment by enumag** [comment] 2016-07-04 08:58
Here you go.

[tata_001.txt](https://github.com/higurashi-mod/tatarigoroshi/files/345945/tata_001.txt) (inserted 516 lines)
[tata_tips_01.txt](https://github.com/higurashi-mod/tatarigoroshi/files/345946/tata_tips_01.txt) (inserted 19 lines)

By the way that logic with remembering the last file where a match was found is not implemented yet. On the other hand I fixed some cases where the line didn't fully match.

**Comment by enumag** [comment] 2016-07-04 09:07
Is it better for you if the script inserts even lines where it is not completely sure and might insert something wrong (like the for now missing logic with the last matching file) or should the script rather do nothing?

**Comment by ItaloKnox** [comment] 2016-07-04 09:10
tata_001 looks a bit confusing, but I think the issue here is that the PS3 voices doesn't cover the entire dialog. Looks fine after a certain point.
tata_tips_01 looks a lot better, though it seems to miss more dialogs than usual.

How hard would it be to let the script have a little more freedom when finding the matches? Let's say, if he can't find an exact match, then look for one that is at least 90% close?

Also, you might want to limit the search to certain folders. In tata_tips_01, the folder S09 comes up at a certain point. Maybe some more logic would narrow down this issue: if the first N lines use the folder X, then limit the search only to X.

**Comment by enumag** [comment] 2016-07-04 09:18
Finding exact match in an index is easy. Non-exact matches are not easy or rather I've never done that before. I'll try using Levenshtein distance algorithm...

**Comment by ItaloKnox** [comment] 2016-07-04 09:26
Take it easy and don't try to rush things. I sent an invite so you can join the repo and push your own changes.

I'm going to off right now, but you are free to upload your scripts after your are satisfied with your code. Just don't forget to put them all into a folder called Update/.

**Comment by enumag** [comment] 2016-07-04 10:26
I've implemented the Levenshtein distance thing and the prefer last file match. Also it's trying to match the beginning of the line so most multi-command lines should be fine now. The script now inserts 54 lines to tata_tips_01 while maintaining a reasonable certainity of them being correct.

tata_001 is missing many lines in the beginning but I couldn't find them manually either so the text is probably different in PS3.

I'll send a pull request once the script finishes running (should take less than an hour).

**Comment by enumag** [comment] 2016-07-04 12:18
See #3

**Comment by cucochukoluko** [comment] 2016-07-04 15:04
I'm starting this right now, yesterday I was out all day. I don't have questions for now. Sorry for the late reply.

**Comment by cucochukoluko** [comment] 2016-07-04 15:05
enumag did you already do it? Yes, it's really easy :P

**Comment by cucochukoluko** [comment] 2016-07-04 15:05
Well I guess I'll do it just in case

**Comment by enumag** [comment] 2016-07-04 15:06
@cucochukoluko Yeah I already did.

**Comment by cucochukoluko** [comment] 2016-07-04 15:10
ok, tell me guys if you need something else.

**Comment by enumag** [comment] 2016-07-04 19:42
@cucochukoluko Sorry for stealing the opportunity from you. It was not as easy as it originally seemed but still only took a few hours. We'll appriciate any ideas for improving the script or the patch. If you're familiar with PHP it would be nice if you could code-review my script when I push it to github.

**Comment by enumag** [comment] 2016-07-04 21:09
If anyone is interested here is the current script: https://github.com/07th-mod/voice-inserter

**Closed as completed by enumag** 2016-07-04 21:09 UTC

**Comment by cucochukoluko** [comment] 2016-07-04 22:36
I don't know php, I was gonna do it in C. But I did take a look at the logic and it's fine, good file handling. No worries, good job man ;).
